spring:
 profiles:
  include: security
 datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb
  username: sa
  password:
 data:
  redis:
   host: localhost
   port: 6379

h2:
 console:
   enabled: true
   path: /h2-console

ec2:
 uri: http://ec2-15-165-3-158.ap-northeast-2.compute.amazonaws.com:8080

